### PR TITLE
ci: add schemathesis github actions workflow

### PR DESCRIPTION
**Pull request by afuetterer**
Hi,

this is a suggestion for you, if you want to keep testing the API with [schemathesis.](https://schemathesis.readthedocs.io/)

I used their [GitHub action](https://github.com/marketplace/actions/schemathesis) in this PR. You can trigger this workflow manually through the actions tab, or for example run the API tests, when a future PR changes api.yaml.

But feel free to ignore this. The config of schemathesis would need some more work to ignore things you dont care about. And also schemathesis does not handle xml out of the box. It prefers JSON APIs.

You would need to add a [custom python xml serializer](https://schemathesis.readthedocs.io/en/stable/how.html#payload-serialization) to test the endpoints that consume xml payloads.

But this might be a first step in the direction of automatic API testing.

What do you think?

Further reading: https://dzone.com/articles/schemathesis-property-based-testing-for-api-schema

### CODE REVIEW

**Comment by cmil** [comment]
Hi @afuetterer,

this is a good and highly appreciated initiative. An extensive test suite is one of the things the dracor-api is still missing. However at the moment we do not automatically deploy changes from GitHub to any of the DraCor environments. So there is no guarantee that for instance staging.dracor.org would actually run the code that the api.yaml in GitHub is supposed to document. Thus the action could fail even though the code if deployed would work without problems.

One solution to this problem could be to have the action set up a test instance of an eXist database with a current build of the dracor-api installed, against which schemathesis is then run.

An alternative would be to implement continuous deployment first and then run the tests against an automatically provisioned development or staging system.

I'd be happy to help with or review changes to this pull request that work towards the first option or to see additional PRs preparing the second way of doing it.

**Comment by afuetterer** [comment]
Hi @cmil,

thank you for the encouragement. I did not want you to merge this right away and run it as part of CI. So I marked this PR as draft now.
I just did not want to throw away the API testing workflow after the workshop in case you need it later.

Yeah, sure, if there is no CD in place, it makes no sense to run the tests against the staging server's API. I added the manual trigger for you to test this workflow.

Schemathesis is written in Python and integrates nicely with flask, django and fastapi services, that's the reason I used it before. But of course there are other ways to test the API: e.g. dredd, cypress or postman.

And yes, if it would be possible to spin up the api in CI with minimal data you could run the tests against localhost.

What do you think?

**Comment by cmil** [comment]
@afuetterer thanks! Yes, let's keep the PR around and we can get back to it when we find time to work on improving CI/CD.

**Comment by cmil** [comment]
Apparently this PR got closed when we deleted the `v1` branch after merging which was not intentional. @afuetterer maybe you can rebase your `schemathesis` branch onto the current dracor-org `main` branch.

**Pull request closed without merging**
