### PR TITLE
ci: add docker group to dependabot config

### PR DESCRIPTION
**Pull request by afuetterer**

### CODE REVIEW

**Comment by cmil** [comment]
What does this do?

**Comment by afuetterer** [comment]
The dependabot will send you a PR, if there is a newer version of the docker base image.

Like "Updates eclipse-temurin from 8-jre to 21-jre"
See: https://github.com/afuetterer/dracor-api/pull/14

Is 21-jre compatible?

**Comment by cmil** [comment]
I think in our case that would only make sense if dependabot could suggest a JRE version that is guaranteed to work with eXist DB. I'm not sure we can simply upgrade to the latest JRE. Until now I have been following the image version used in https://github.com/peterstadler/existdb-docker/blob/main/Dockerfile which our Dockerfile was derived from, which is why we are still running `8-jre` at the moment. That may be more conservative than necessary, though. The [eXist documentation](http://exist-db.org/exist/apps/doc/basic-installation) gives Java 8 as the minimum requirement but doesn't exactly say what's the latest supported Java version. A short search at the eXist reveals that they are using JDK 17 in a lot of places. So an upgrade to `eclipse-temurin:21-jre` may indeed be premature.

**Comment by afuetterer** [comment]
Alright, if there is no way to test the functionality of the docker container (and thus the image is working), then I will close this PR.

**Pull request closed without merging**
